import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BoxItemsProvider } from "@/useContext/context";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function ClientLayout({ children }: { children: React.ReactNode }) {
  return <BoxItemsProvider>{children}</BoxItemsProvider>;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
